### ISSUE TITLE
Interaction with bios control? 

### ISSUE THREAD

**Issue by dashbad** [desbma/hddfancontrol#1]
How does this script interact with bios controlled fan speed?

My mobo controls the speed of all fans using the cpu temp and I would like to use this script to "override" this control for 2 of the fans. What will happen when the bios and script disagree on the correct speed for a particular fan?

**Comment by desbma** [comment]
Hi,

When you boot Linux, by default the fans are controlled by the BIOS. When hddfancontrol first starts, [it enables manual control by the OS](https://github.com/desbma/hddfancontrol/blob/0d63bfdb6a914aff3f10a9997fe19cc67b564cc7/hddfancontrol/__init__.py#L324), from there the fan speed is always set by software, never the BIOS, unless you reboot.
