### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by Fahrenheit92** [desbma/hddfancontrol#13]
When running the Test to find the PWM Values on the 4th line the output is as follows

`Test of fan #1 --------------------------------------------------------------------------------
Stopping fan                                                                             [ KO ]`

I guess it should read [OK] instead ;)

**Comment by desbma** [comment]
I'm not sure this is a typo, this can mean the fan takes a long time to react and does not stop when it should during the test.

Can you please provide full command and output?

**Comment by desbma** [comment]
I'm closing this then.
