### ISSUE TITLE
Min Fan Speed Setting not respected

### ISSUE THREAD

**Issue by Fahrenheit92** [desbma/hddfancontrol#14]
Even though I am running a min Fan Speed Setting the fan speed is still commanded below that threshold, at least according to the log. I am running the systemd service.

ARGS: `--min-fan-speed-prct 10`

LOG:
`Jan 13 16:04:19 nasty hddfancontrol[31549]: INFO [Main] Maximum drive temperature: 30 C`
`Jan 13 16:04:19 nasty hddfancontrol[31549]: INFO [Fan #1] Setting fan speed to 0%`
`Jan 13 16:04:39 nasty hddfancontrol[31549]: INFO [Main] Maximum drive temperature: 31 C`
`Jan 13 16:04:39 nasty hddfancontrol[31549]: INFO [Fan #1] Setting fan speed to 5%`

Cheers

**Comment by Fahrenheit92** [comment]
After having looked at the code seems to be a logging Issue I suggest to change file `__init__.py` Line 322 from
```python
self.logger.info("Setting fan speed to %u%%" % (speed_prct))
```
to
```python
# Only show change in Logfile, when requested speed_prct is greater then min_prct
    if (speed_prct > min_prct):
      self.logger.info("Setting fan speed to %u%%" % (speed_prct))
```

**Comment by desbma** [comment]
Indeed, that logging statement is misleading.
