### ISSUE TITLE
Feature request: use temp from all disks when '-d' parameter is ommited

### ISSUE THREAD

**Issue by lopatoid** [desbma/hddfancontrol#20]
I have a lot of disks and I need to edit config file every time I remove or add HDD.
For a workaround I use _hddfancontrol -d /dev/sd?_ but it fails when usb stick is inserted (hddfancontrol can't read S.M.A.R.T from usb stick and refuses to start). I see two ways to fix it:
1) use temperature from all disks when '-d' parameter is ommited.
2) _hddfancontrol must continue to work even if it can't read  S.M.A.R.T data

**Comment by desbma** [comment]
Try `hddfancontrol -d $(ls /dev/disk/by-id/ata-* | grep -Ev 'part[0-9]+$') ...`

**Comment by lopatoid** [comment]
Thanks!
