### ISSUE TITLE
template for hddfancontrol.conf

### ISSUE THREAD

**Issue by akrea** [desbma/hddfancontrol#38]
Hi

This is not a real issue, but I didn't know how to contact you otherwise. In order to run the deamon I have to provide `HDDFANCONTROL_ARGS=""` in `hddfancontrol.conf`. Unfortunately I have no idea of the syntax to use (e.g. does every line need a dash in front of it or semicolon to end the line. or is it just on line of arguments like the hddfancontrol command). Maybe this is common knowledge among programmers and I'm just not there yet... If you could point me to the right documentation would be most appreciated.

Thank you!

**Comment by desbma** [comment]
>  is it just on line of arguments like the hddfancontrol command

Yes it is the command line arguments.

**Comment by akrea** [comment]
Does this look right (i have no idea how i could check that otherwise...).
```
HDDFANCONTROL_ARGS="-d /dev/sda /dev/sdb -p /sys/class/hwmon/hwmon1/pwm4 /sys/class/hwmon/hwmon1/pwm5 --pwm-start-value 200 200 --pwm-stop-value 45 60 --min-fan-speed-prct 10 -i 60 --spin-down-time 7200"
```

**Comment by desbma** [comment]
Run it, and it will tell you if there is an incorrect argument.

**Comment by akrea** [comment]
I think its working. Will closely monitor this next few days.
Thank you!!!
