### ISSUE TITLE
Please add SAS branch to main Readme

### ISSUE THREAD

**Issue by exodus454** [desbma/hddfancontrol#49]
It works fantastically and got rid of all the issues I was having with SAS drives. The only way I stumbled into it was a closed issue which is pretty buried.

Please put some directions on the master Readme to the SAS branch!

**Comment by desbma** [comment]
The SAS branch has been merged into master for a while now, and that code released in version 1.6.0.
It you encounter any problem with SAS drives, please open a new issue as I can't test it myself.
