### ISSUE TITLE
hddfancontrol package also available in Fedora

### ISSUE THREAD

**Issue by TC01** [desbma/hddfancontrol#5]
I noticed [this commit](https://github.com/desbma/hddfancontrol/commit/a39ede133a99cdca74c110aa0e750c5ea4353354) as part of the 1.2.5 changes to mention an AUR package, so I figured I'd mention that hddfancontrol is also available [in Fedora's repositories](https://apps.fedoraproject.org/packages/hddfancontrol), packaged (by me) as ```hddfancontrol```, and can be installed via ```dnf install hddfancontrol```, in case you'd want to mention that on the README as well. :)

**Comment by desbma** [comment]
Thank you very much for taking the time to package this to Fedora ! I will definitely mention this in the README.

Please don't hesitate to report portability or packaging issues here (even minor).

I plan to add a systemd service file soon, this may be useful for Fedora too.
