### ISSUE TITLE
PWM Path seems read only, not able to control fan speed

### ISSUE THREAD

**Issue by N20Visuals** [desbma/hddfancontrol#62]
Hi, 

i'm currently trying to get your script running on TrueNAS Scale Electric Eel through docker. 

So far i've managed to get everything working, the only trouble is that hddfancontrol seems to crash instantly if i try to start the docker container. 
The error i keep getting is "ERRNO 13 - Permission denied" 

The container is running in privileged mode and as user root. When i check the file paths where the pwm entities are stored i can see that all of them are read only. is this normal or did i miss a step i need to do to be able to control the fans? 
i know that docker creates an additional layer but maybe there is a easy fix that i just keep missing?

**Comment by desbma** [comment]
hddfancontrol is a low level system tool, designed to run on the host system.
This issue is due to your Docker setup, pwm files are not supposed to be read only.
I can't help you with that.
